# Generated by Django 4.0 on 2024-04-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('artist', models.CharField(max_length=255)),
                ('image_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('genres', models.JSONField()),
                ('attrs', models.JSONField()),
            ],
        ),
    ]
